import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import {HeaderWrapper} from "@/components/header/HeaderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children } = props
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
